name: "build-scaffold-tauri-app"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-scaffold-tauri-app:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Extend space
        uses: ./.github/actions/extend-space

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - uses: cachix/cachix-action@v14
        with:
          name: darksoil-studio

      - name: Build scaffold-tauri-app
        run: |
          nix build -L .#scaffold-tauri-app

      - name: Cache scaffold-tauri-app
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          cachix push darksoil-studio $(nix path-info .#scaffold-tauri-app)
          cachix pin darksoil-studio scaffold-tauri-app $(nix path-info .#scaffold-tauri-app)

