name: "cache-devshells"
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push: 
    branches: [ main ]

jobs:
  cache-devshells:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-ci

      - uses: cachix/cachix-action@v14
        with:
          name: holochain-open-dev

      - uses: cachix/cachix-action@v14
        with:
          name: darksoil-studio

      - name: Cache holochainTauriDev
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.DARKSOIL_CACHIX_AUTH_TOKEN }}"
        run: |
          nix develop --profile holochainTauriDev -c true .#holochainTauriDev
          cachix push darksoil-studio holochainTauriDev
          nix develop --profile holochainTauriAndroidDev -c true .#holochainTauriAndroidDev
          cachix push darksoil-studio holochainTauriAndroidDev
          nix build .#holochainTauriRust -L
          nix build .#androidTauriRust -L
          cachix pin darksoil-studio holochainTauriRust $(nix path-info --accept-flake-config .#holochainTauriRust)
          cachix pin darksoil-studio androidTauriRust $(nix path-info --accept-flake-config .#androidTauriRust)
